spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: Gestion-Municipio
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/gestion/municipio/**
        - id: Gestion-Provincia
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/gestion/provincia/**
        - id: Gestion-AreaSalud
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/gestion/areaSalud/**
        - id: Gestion-Empleado
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/gestion/empleado/**
        - id: Gestion-Entidad
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/gestion/entidad/**
        - id: Gestion-EntidadEmpleado
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/gestion/entidadEmpleado/**
        - id: Gestion-ZonaTransporte
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/gestion/zonaTransporte/**
        - id: Logs-Estado
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/login/estado/**
        - id: Logs-Registro
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/login/registro/**
        - id: Logs-Rol
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/login/rol/**
        - id: Logs-Sexo
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/login/sexo/**
        - id: Logs-Usuario
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/login/usuario/**
        - id: Logs-Login
          uri: http://localhost:8086
          predicates:
            - Path=/login/**
  config: #Configuración de config server
    import: optional:configserver:http://localhost:8888

eureka:
  server:
    port : 8761
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/