spring:
  application:
    name: Geo
  config: #Configuración de config server
    import: optional:configserver:http::localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8088