spring:
  application:
    name: Eureka Server
  config: #Configuración de config server
    import: optional:configserver:http::localhost:8888

server:
  port: 8761

eureka: #Configuración de Eureka
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #Para que eureka no se registe en el servidor
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/