spring:
  application:
    name: Automatizacion
  banner:
    location: templates/banner.txt

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8089
